/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff9e7',
        'surface-dim': '#dfdac6',
        'surface-bright': '#fff9e7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f9f4df',
        'surface-container': '#f4eeda',
        'surface-container-high': '#eee8d4',
        'surface-container-highest': '#e8e2cf',
        'on-surface': '#1e1c10',
        'on-surface-variant': '#4b4731',
        'inverse-surface': '#333123',
        'inverse-on-surface': '#f7f1dc',
        outline: '#7c785f',
        'outline-variant': '#cdc7aa',
        'surface-tint': '#695f00',
        primary: '#695f00',
        'on-primary': '#ffffff',
        'primary-container': '#ffea00',
        'on-primary-container': '#736900',
        'inverse-primary': '#dbc900',
        secondary: '#5556a2',
        'on-secondary': '#ffffff',
        'secondary-container': '#aaacfe',
        'on-secondary-container': '#3b3d87',
        tertiary: '#006a68',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4dfffc',
        'on-tertiary-container': '#007472',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#fae500',
        'primary-fixed-dim': '#dbc900',
        'on-primary-fixed': '#1f1c00',
        'on-primary-fixed-variant': '#4f4800',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c1c1ff',
        'on-secondary-fixed': '#0e0c5c',
        'on-secondary-fixed-variant': '#3d3e88',
        'tertiary-fixed': '#45faf7',
        'tertiary-fixed-dim': '#00ddda',
        'on-tertiary-fixed': '#00201f',
        'on-tertiary-fixed-variant': '#00504f',
        background: '#fff9e7',
        'on-background': '#1e1c10',
        'surface-variant': '#e8e2cf',
        'success-vibrant': '#22C55E',
        'alert-error': '#EF4444',
        'neutral-surface': '#F8F9FA',
        'on-yellow-text': '#0F172A',
        'navy-deep': '#0F172A',
        'slate-serious': '#64748B',
        'alert-warning': '#F59E0B',
        'surface-card': '#FFFFFF',
        'border-subtle': '#E2E8F0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'base-unit': '4px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        gutter: '16px',
        'container-max-width': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0px 4px 6px -1px rgba(15, 23, 42, 0.1), 0px 2px 4px -2px rgba(15, 23, 42, 0.1)',
      },
    },
  },
  plugins: [],
};
